import type { User, Session, FeedPost, Event, Challenge, Notification } from '../types'

export const DEMO_USER: User = {
  id: 'u1',
  email: 'alex@sparr.com',
  role: 'athlete',
  displayName: 'Alex Müller',
  username: 'alex_sparr',
  bio: 'Muay Thai & Boxing | 5 Jahre Erfahrung | Zürich',
  location: 'Zürich, CH',
  sports: ['muay_thai', 'boxing'],
  weightClass: '67kg',
  gym: 'SPARR Gym Zürich',
  verified: true,
  followersCount: 312,
  followingCount: 89,
  createdAt: '2024-01-15T10:00:00Z',
  onboardingComplete: true,
  subscriptionTier: 'pro',
}

export const DEMO_SESSIONS: Session[] = [
  {
    id: 's1',
    userId: 'u1',
    title: 'Muay Thai Sparring',
    type: 'sparring',
    sport: 'muay_thai',
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    endedAt: new Date(Date.now() - 84600000).toISOString(),
    durationMinutes: 60,
    intensity: 4,
    calories: 680,
    rounds: 6,
    mood: 'great',
    notes: 'Gute Leistung heute. Kombinationen klappen immer besser.',
    isPublic: true,
    isRealCheckin: true,
  },
  {
    id: 's2',
    userId: 'u1',
    title: 'Bag Work + Conditioning',
    type: 'bag',
    sport: 'boxing',
    startedAt: new Date(Date.now() - 172800000).toISOString(),
    endedAt: new Date(Date.now() - 169200000).toISOString(),
    durationMinutes: 90,
    intensity: 3,
    calories: 520,
    mood: 'good',
    isPublic: true,
    isRealCheckin: false,
  },
  {
    id: 's3',
    userId: 'u1',
    title: 'Drilling Session',
    type: 'drilling',
    sport: 'muay_thai',
    startedAt: new Date(Date.now() - 259200000).toISOString(),
    endedAt: new Date(Date.now() - 256200000).toISOString(),
    durationMinutes: 50,
    intensity: 2,
    calories: 310,
    mood: 'ok',
    isPublic: false,
    isRealCheckin: false,
  },
  {
    id: 's4',
    userId: 'u1',
    title: 'Morgenrun',
    type: 'run',
    sport: 'boxing',
    startedAt: new Date(Date.now() - 345600000).toISOString(),
    endedAt: new Date(Date.now() - 343200000).toISOString(),
    durationMinutes: 40,
    intensity: 3,
    calories: 380,
    distanceKm: 6.2,
    mood: 'good',
    isPublic: true,
    isRealCheckin: false,
  },
]

export const DEMO_POSTS: FeedPost[] = [
  {
    id: 'p1',
    userId: 'u2',
    authorName: 'Sara Kaya',
    authorUsername: 'sara_fights',
    authorVerified: true,
    content: 'Heute erste Sparring-Runde nach Verletzung. Fühlt sich gut an zurück zu sein. Der Körper hat alles noch drauf.',
    type: 'session_share',
    likesCount: 47,
    commentsCount: 8,
    isLiked: false,
    tags: ['sparring', 'comeback', 'boxing'],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'p2',
    userId: 'u3',
    authorName: 'Coach Radu',
    authorUsername: 'radu_coach',
    authorVerified: true,
    content: 'Erinnerung: Heute Abend Pad-Training um 19:00. Bringt eure volle Energie. Wir arbeiten an Teep-Kombinationen.',
    type: 'post',
    likesCount: 23,
    commentsCount: 5,
    isLiked: true,
    tags: ['training', 'muaythai'],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'p3',
    userId: 'u4',
    authorName: 'Marco Benz',
    authorUsername: 'marco_benz_mt',
    authorVerified: false,
    content: '7-Tage Streak! Jeden Tag trainiert diese Woche. Körper schreit aber der Kopf will mehr.',
    type: 'achievement',
    likesCount: 91,
    commentsCount: 14,
    isLiked: false,
    tags: ['streak', 'consistency'],
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'p4',
    userId: 'u5',
    authorName: 'SPARR Gym Zürich',
    authorUsername: 'sparr_gym_zh',
    authorVerified: true,
    content: 'Swiss Open 2025 – Anmeldungen sind jetzt offen! 15 Gewichtsklassen, 3 Kampfsportarten. Meldet euch jetzt an.',
    type: 'post',
    likesCount: 156,
    commentsCount: 32,
    isLiked: false,
    tags: ['event', 'tournament', 'swiss'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
]

export const DEMO_EVENTS: Event[] = [
  {
    id: 'e1',
    organizerId: 'u5',
    gymId: 'g1',
    title: 'Swiss Open 2025',
    sport: ['boxing', 'muay_thai', 'kickboxing'],
    type: 'tournament',
    status: 'registration_open',
    startDate: '2025-09-13T09:00:00Z',
    endDate: '2025-09-14T18:00:00Z',
    location: 'Eulachhalle',
    city: 'Winterthur',
    country: 'CH',
    description: 'Das grösste Kampfsport-Turnier der Deutschschweiz. Alle Levels willkommen.',
    maxParticipants: 300,
    registeredCount: 187,
    weightClasses: ['54kg', '57kg', '60kg', '63.5kg', '67kg', '71kg', '75kg', '+75kg'],
    entryFee: 65,
    currency: 'CHF',
  },
  {
    id: 'e2',
    organizerId: 'u3',
    gymId: 'g1',
    title: 'Trainer-Seminar: Teep & Push Kick',
    sport: ['muay_thai'],
    type: 'seminar',
    status: 'registration_open',
    startDate: '2025-07-20T10:00:00Z',
    endDate: '2025-07-20T14:00:00Z',
    location: 'SPARR Gym Zürich',
    city: 'Zürich',
    country: 'CH',
    description: 'Fortgeschrittenes Seminar zur Technik des Teep. Mit Coach Radu.',
    maxParticipants: 20,
    registeredCount: 14,
    weightClasses: [],
    entryFee: 45,
    currency: 'CHF',
  },
  {
    id: 'e3',
    organizerId: 'u5',
    gymId: 'g1',
    title: 'Open Mat BJJ',
    sport: ['bjj'],
    type: 'open_mat',
    status: 'published',
    startDate: '2025-07-05T14:00:00Z',
    endDate: '2025-07-05T17:00:00Z',
    location: 'SPARR Gym Zürich',
    city: 'Zürich',
    country: 'CH',
    description: 'Offenes Sparring für alle Gürtelgrade. Keine Anmeldung nötig.',
    registeredCount: 0,
    weightClasses: [],
    entryFee: 0,
    currency: 'CHF',
  },
]

export const DEMO_CHALLENGES: Challenge[] = [
  {
    id: 'c1',
    creatorId: 'u5',
    title: '100 Runden Juli',
    description: 'Schaffe 100 Sparring-Runden im Juli. Egal ob Boxing, MT oder MMA.',
    type: 'sparring_rounds',
    target: 100,
    unit: 'Runden',
    startDate: '2025-07-01T00:00:00Z',
    endDate: '2025-07-31T23:59:59Z',
    isPublic: true,
    participantCount: 34,
  },
  {
    id: 'c2',
    creatorId: 'u3',
    title: '7-Tage Streak',
    description: 'Trainiere 7 Tage in Folge ohne Pause.',
    type: 'streak',
    target: 7,
    unit: 'Tage',
    startDate: '2025-06-01T00:00:00Z',
    endDate: '2025-08-31T23:59:59Z',
    isPublic: true,
    participantCount: 89,
  },
  {
    id: 'c3',
    creatorId: 'u2',
    title: 'Summer Run 50km',
    description: '50km laufen im Sommer zur Grundlagenausdauer.',
    type: 'distance',
    target: 50,
    unit: 'km',
    startDate: '2025-06-01T00:00:00Z',
    endDate: '2025-08-31T23:59:59Z',
    isPublic: true,
    participantCount: 22,
  },
]

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    type: 'like',
    title: 'Neue Reaktion',
    body: 'Sara Kaya gefällt dein Session-Post.',
    read: false,
    actorName: 'Sara Kaya',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'n2',
    userId: 'u1',
    type: 'follow',
    title: 'Neuer Follower',
    body: 'Marco Benz folgt dir jetzt.',
    read: false,
    actorName: 'Marco Benz',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'n3',
    userId: 'u1',
    type: 'event_registration_confirmed',
    title: 'Anmeldung bestätigt',
    body: 'Deine Anmeldung für Swiss Open 2025 wurde bestätigt.',
    read: true,
    actionUrl: '/events/e1',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'n4',
    userId: 'u1',
    type: 'broadcast',
    title: 'Trainingsupdate',
    body: 'Coach Radu: Heute Abend Teep-Training 19:00 Uhr.',
    read: true,
    actorName: 'Coach Radu',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
]
